### ISSUE TITLE
Unable to access Github Enterprise repository using git-refs datasource.

### ISSUE THREAD

**Issue by bc-lee** [mend/renovate-ce-ee#200]
I'm currently using WhiteSource Renovate On-Premises, and when using git-refs I can't seem to resolve the repository.

Target repository's `renovate.json5`:
```json5
{
  ...,
  "regexManagers": [
    {
      "fileMatch": ["^.github\\/workflows\\/[^/]+\\.ya?ml$"],
      "matchStrings": ["path-to/target-repository@(?<currentDigest>.*?)\n"],
      "depNameTemplate": "https://path.to.ghe/path-to/target-repository",
      "versioningTemplate": "git",
      "datasourceTemplate": "git-refs",
      "currentValueTemplate": "master"
    },
  ],
}
```

I get errors like this:

```
DEBUG: Dependency https://path.to.ghe/path-to/target-repository has unsupported value master (repository=path-to/source-repository)
ERROR: lookupUpdates error (repository=path-to/source-repository, packageFile=.github/workflows/build.yml)
       "currentDigest": "/*redacted*/",
       "currentValue": "master",
       "datasource": "git-refs",
       "depName": "https://path.to.ghe/path-to/target-repository",
       "digestOneAndOnly": undefined,
       "followTag": null,
       "lockedVersion": undefined,
       "pinDigests": false,
       "rollbackPrs": false,
       "isVulnerabilityAlert": undefined,
       "updatePinnedDependencies": true,
       "unconstrainedValue": undefined,
       "err": {
         "task": {
           "commands": [
             "ls-remote",
             "https://path.to.ghe/path-to/target-repository"
           ],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "fatal: could not read Username for 'https://path.to.ghe': No such device or address\n",
         "stack": "Error: fatal: could not read Username for 'https://path.to.ghe': No such device or address\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.js:30:33)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.js:21:33)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:95:45\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:93:16)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:77:46)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)"
       }
``````

But when I run `renovatebot/renovate` directly with the following config, it works successfully.

`config.js`:
```js
const jsonwebtoken = require("jsonwebtoken");
const fetch = require("node-fetch");

const githubComToken = "/*redacted*/";
const endpoint = "https://path.to.ghe/api/v3";
const appId = /*redacted*/;
const installationId = /*redacted*/;
const privateKey = "/*redacted*/"

module.exports = async function () {
  now = Math.floor(Date.now() / 1000)
  const nowWithSafetyMargin = now - 30;
  const expiration = nowWithSafetyMargin + 60 * 10;
  const payload = {
    iat: nowWithSafetyMargin,
    exp: expiration,
    iss: appId
  };
  const jwt = jsonwebtoken.sign(payload, privateKey, {
    algorithm: "RS256"
  });
  const response = await fetch(endpoint + "/app/installations/" + installationId + "/access_tokens", {
    method: "POST",
    headers: {
      "Authorization": "Bearer " + jwt,
      "Accept": "application/vnd.github.v3+json",
    },
  });
  if (!response.ok) {
    throw new Error("Http returned " + response.status);
  }
  const {token} = await response.json()

  return {
    token: "x-access-token:" + token,
    endpoint: endpoint,
    username: "/*redacted*/",
    gitAuthor: "/*redacted*/",
    hostRules: [{
      hostType: "github",
      matchHost: 'github.com',
      token: githubComToken,
      username: "/*redacted*/",
      gitAuthor: "/*redacted*/"
    }],
  };
}
```

**Comment by rarkins** [comment]
Fixed in v6
