### ISSUE TITLE
`Cannot read properties of undefined` errors in the logs on some Issue Hook events

### ISSUE THREAD

**Issue by jamietanna** [mend/renovate-ce-ee#328]
I've noticed a few of these events occurring in my logs:

```
 INFO: Received webhook event (repository=tanna.dev/jvt.me)
       "event": "issue"
ERROR: error processing event
       "eventType": "Issue Hook",
       "err": {
         "message": "Cannot read properties of undefined (reading 'includes')",
         "stack": "TypeError: Cannot read properties of undefined (reading 'includes')\n    at /usr/src/app/src/community.js:1:48678\n    at /usr/src/app/src/community.js:1:49002\n    at t.processWebhook (/usr/src/app/src/community.js:1:50277)\n    at /usr/src/app/src/community.js:1:45645\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/usr/src/app/node_modules/express/lib/router/route.js:144:13)\n    at /usr/src/app/src/community.js:1:46067"
       }
```

One such webhook event causing this error:

<details>

```json
{
  "object_kind": "issue",
  "event_type": "issue",
  "user": {
    "id": 9274847,
    "name": "Tanna[bot]",
    "username": "jamietanna_bot",
    "avatar_url": "https://secure.gravatar.com/avatar/82b22da4266ab15b812a78f9a9bc3ec0?s=80&d=identicon",
    "email": "[REDACTED]"
  },
  "project": {
    "id": 1745856,
    "name": "jvt.me",
    "description": "My personal website",
    "web_url": "https://gitlab.com/tanna.dev/jvt.me",
    "avatar_url": "https://gitlab.com/uploads/-/system/project/avatar/1745856/profile.jpg",
    "git_ssh_url": "git@gitlab.com:tanna.dev/jvt.me.git",
    "git_http_url": "https://gitlab.com/tanna.dev/jvt.me.git",
    "namespace": "tanna.dev",
    "visibility_level": 20,
    "path_with_namespace": "tanna.dev/jvt.me",
    "default_branch": "main",
    "ci_config_path": "",
    "homepage": "https://gitlab.com/tanna.dev/jvt.me",
    "url": "git@gitlab.com:tanna.dev/jvt.me.git",
    "ssh_url": "git@gitlab.com:tanna.dev/jvt.me.git",
    "http_url": "https://gitlab.com/tanna.dev/jvt.me.git"
  },
  "object_attributes": {
    "author_id": 9274847,
    "closed_at": null,
    "confidential": false,
    "created_at": "2022-10-17 14:13:03 UTC",
    "description": "This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.\n\n## Repository problems\n\nRenovate tried to run on this repository, but found these problems.\n\n - WARN: Package lookup failures\n\n## Pending Approval\n\nThese branches will be created by Renovate only once you click their checkbox below.\n\n - [ ] <!-- approve-branch=renovate/rake-13.x-lockfile -->Update dependency rake to v13.0.6\n - [ ] <!-- approve-branch=renovate/alpine-3.x -->Update alpine Docker tag to v3.18\n - [ ] <!-- approve-branch=renovate/etc-1.x-lockfile -->Update dependency etc to v1.4.2\n - [ ] <!-- approve-branch=renovate/git-1.x-lockfile -->Update dependency git to v1.18.0\n - [ ] <!-- approve-branch=renovate/html-proofer-3.x-lockfile -->Update dependency html-proofer to v3.19.4\n - [ ] <!-- approve-branch=renovate/json-2.x-lockfile -->Update dependency json to v2.6.3\n - [ ] <!-- approve-branch=renovate/microformats-4.x-lockfile -->Update dependency microformats to v4.5.0\n - [ ] <!-- approve-branch=renovate/rspec-3.x-lockfile -->Update dependency rspec to v3.12.0\n - [ ] <!-- approve-branch=renovate/klakegg-hugo-0.x -->Update klakegg/hugo Docker tag to v0.111.3\n - [ ] <!-- approve-branch=renovate/html-proofer-5.x-lockfile -->Update dependency html-proofer to v5\n - [ ] <!-- approve-branch=renovate/json-schema-4.x-lockfile -->Update dependency json-schema to v4\n - [ ] <!-- approve-branch=renovate/docker-24.x -->Update docker Docker tag to v24\n - [ ] <!-- approve-all-pending-prs -->🔐 **Create all pending approval MRs at once** 🔐\n\n\n---\n\n### ⚠ Dependency Lookup Warnings ⚠\n\n-   Renovate failed to look up the following dependencies: `Failed to look up docker package registry.gitlab.com/jamietanna/jvt.me/hugo-base`, `Failed to look up docker package registry.gitlab.com/jamietanna/jvt.me/ruby-base`.\n\nFiles affected: `Dockerfile`, `Dockerfile.branch`\n\n---\n\n\n## Open\n\nThese updates have all been created already. Click a checkbox below to force a retry/rebase of any.\n\n - [ ] <!-- rebase-branch=renovate/pin-dependencies -->[Pin dependencies](!892) (`alpine`, `docker`, `klakegg/hugo`)\n\n## Detected dependencies\n\n<details><summary>bundler</summary>\n<blockquote>\n\n<details><summary>.rake/Gemfile</summary>\n\n - `etc undefined`\n - `git undefined`\n - `html-proofer undefined`\n - `json undefined`\n - `json-schema undefined`\n - `kwalify undefined`\n - `microformats undefined`\n - `rake undefined`\n - `rspec undefined`\n\n</details>\n\n</blockquote>\n</details>\n\n<details><summary>dockerfile</summary>\n<blockquote>\n\n<details><summary>Dockerfile</summary>\n\n - `registry.gitlab.com/jamietanna/jvt.me/hugo-base 0.68.3`\n\n</details>\n\n<details><summary>Dockerfile.branch</summary>\n\n - `registry.gitlab.com/jamietanna/jvt.me/hugo-base 0.68.3`\n - `registry.gitlab.com/jamietanna/jvt.me/ruby-base v2`\n\n</details>\n\n<details><summary>Dockerfile.hugo-base</summary>\n\n - `klakegg/hugo 0.101.0-ext-alpine`\n\n</details>\n\n<details><summary>Dockerfile.ruby-base</summary>\n\n - `alpine 3.11`\n\n</details>\n\n</blockquote>\n</details>\n\n<details><summary>gitlabci</summary>\n<blockquote>\n\n<details><summary>.gitlab-ci.yml</summary>\n\n - `docker 19.03`\n - `docker 19.03-dind`\n\n</details>\n\n</blockquote>\n</details>\n\n<details><summary>gomod</summary>\n<blockquote>\n\n<details><summary>go.mod</summary>\n\n - `go 1.18`\n\n</details>\n\n</blockquote>\n</details>\n\n---\n\n- [ ] <!-- manual job -->Check this box to trigger a request for Renovate to run again on this repository",
    "discussion_locked": null,
    "due_date": null,
    "id": 117037850,
    "iid": 1261,
    "last_edited_at": "2023-09-28 19:03:11 UTC",
    "last_edited_by_id": 9274847,
    "milestone_id": null,
    "moved_to_id": null,
    "duplicated_to_id": null,
    "project_id": 1745856,
    "relative_position": 2130841252,
    "state_id": 1,
    "time_estimate": 0,
    "title": "Dependency Dashboard",
    "updated_at": "2023-09-28 19:03:11 UTC",
    "updated_by_id": 9274847,
    "weight": null,
    "health_status": null,
    "url": "https://gitlab.com/tanna.dev/jvt.me/-/issues/1261",
    "total_time_spent": 0,
    "time_change": 0,
    "human_total_time_spent": null,
    "human_time_change": null,
    "human_time_estimate": null,
    "assignee_ids": [

    ],
    "assignee_id": null,
    "labels": [

    ],
    "state": "opened",
    "severity": "unknown",
    "customer_relations_contacts": [

    ],
    "action": "update"
  },
  "labels": [

  ],
  "changes": {
  },
  "repository": {
    "name": "jvt.me",
    "url": "git@gitlab.com:tanna.dev/jvt.me.git",
    "description": "My personal website",
    "homepage": "https://gitlab.com/tanna.dev/jvt.me"
  }
}
```

Request headers:

```
Content-Type: application/json
User-Agent: GitLab/16.5.0-pre
X-Gitlab-Event: Issue Hook
X-Gitlab-Webhook-UUID: 4307e9d9-7be4-453b-b80f-96324a93eead
X-Gitlab-Instance: https://gitlab.com
X-Gitlab-Token: [REDACTED]
X-Gitlab-Event-UUID: 20c5cee6-ba48-4389-99e7-82868854712e
```

</details>

**Comment by PhilipAbed** [comment]
payload.changes?
changes description is empty, we should ignore this hook, so this doesn't impact any flow.
