### ISSUE TITLE
Empty reply from server

### ISSUE THREAD

**Issue by missedone** [mend/renovate-ce-ee#406]
hi 
I have the renovate-ce-gitlab (`ghcr.io/mend/renovate-ce:6.7.0-full`) installed in our AWS EKS cluster.
I see the discovery worked, the onboard PRs were created (though somehow not all repos have the PR), once i merged the onboarding PR, i don't see the renovate PR created, below is the debug log in the renovate-ce pod

PS: it happened on both Java, Go repos (didn't have the chance to verify on repos with other programming language)

```
DEBUG: Repository result: unknown-error, status: unknown, enabled: undefined, onboarded: undefined (repository=org1/repo1)
DEBUG: Repository timing splits (milliseconds) (repository=org1/repo1)
       "splits": {},
       "total": 11333
DEBUG: Package cache statistics (repository=org1/repo1)
       "get": {"count": 0},
       "set": {"count": 0}
DEBUG: Package lookup durations (repository=org1/repo1)
DEBUG: dns cache (repository=org1/repo1)
       "hosts": []
 INFO: Repository finished (repository=org1/repo1)
       "cloned": false,
       "durationMs": 11333
DEBUG: Checking file package cache for expired items
DEBUG: Deleted 0 of 0 file cached entries in 2ms
DEBUG: Renovate exiting
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "ad710b8041",
           "repository": "org1/repo1",
           "err": {
             "task": {
               "commands": [
                 "ls-remote",
                 "--heads",
                 "https://**redacted**@gitlab.company.com/org1/repo1.git"
               ],
               "format": "utf-8",
               "parser": "[function]"
             },
             "message": "fatal: unable to access 'https://gitlab.company.com/org1/repo1.git/': Empty reply from server\n",
             "stack": "Error: fatal: unable to access 'https://gitlab.company.com/org1/repo1.git/': Empty reply from server\n\n    at Object.action (/usr/src/app/node_modules/renovate/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:42:29)\n    at PluginStore.exec (/usr/src/app/node_modules/renovate/node_modules/simple-git/src/lib/plugins/plugin-store.ts:29:29)\n    at /usr/src/app/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:127:42\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:124:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:100:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/renovate/node_modules/simple-git/dist/cjs/index.js:55:24)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
           },
           "msg": "Repository has unknown error"
         }
       ]
ERROR: renovate cli error
       "err": {
         "cmd": "/bin/sh -c /usr/bin/node_default /usr/src/app/node_modules/renovate/dist/renovate.js",
         "stderr": "",
         "stdout": "",
         "options": {
           "encoding": "utf-8",
           "env": [
             "KUBERNETES_SERVICE_PORT_HTTPS",
             "RENOVATE_BINARY_SOURCE",
             "KUBERNETES_SERVICE_PORT",
             "USER_ID",
             "RENOVATE_X_EXEC_GPID_HANDLE",
             "LOG_LEVEL",
             "HOSTNAME",
             "RENOVATE_CE_MEND_RENOVATE_CE_SERVICE_PORT",
             "RENOVATE_CE_MEND_RENOVATE_CE_PORT_80_TCP_ADDR",
             "DOTNET_ROOT",
             "DOTNET_CLI_TELEMETRY_OPTOUT",
             "MEND_RNV_SQLITE_FILE_PATH",
             "DOTNET_SKIP_FIRST_TIME_EXPERIENCE",
             "RENOVATE_CE_MEND_RENOVATE_CE_PORT_80_TCP",
             "MEND_RNV_WEBHOOK_SECRET",
             "RENOVATE_CE_MEND_RENOVATE_CE_PORT_80_TCP_PORT",
             "GITHUB_COM_TOKEN",
             "ENV",
             "PWD",
             "MEND_RNV_LICENSE_KEY",
             "MEND_RNV_ACCEPT_TOS",
             "MEND_RNV_CRON_JOB_SCHEDULER",
             "NO_UPDATE_NOTIFIER",
             "MEND_RNV_RENOVATE_VERSION",
             "USER_NAME",
             "HOME",
             "USER_HOME",
             "LANG",
             "KUBERNETES_PORT_443_TCP",
             "CARGO_HOME",
             "GOSUMDB",
             "MEND_RNV_ENDPOINT",
             "RENOVATE_CE_MEND_RENOVATE_CE_PORT_80_TCP_PROTO",
             "GEM_HOME",
             "PIP_DISABLE_PIP_VERSION_CHECK",
             "SHLVL",
             "RENOVATE_ONBOARDING_CONFIG",
             "RENOVATE_CE_MEND_RENOVATE_CE_PORT",
             "BASH_ENV",
             "KUBERNETES_PORT_443_TCP_PROTO",
             "npm_config_fund",
             "CONTAINERBASE",
             "MEND_RNV_PLATFORM",
             "KUBERNETES_PORT_443_TCP_ADDR",
             "MEND_RNV_AUTODISCOVER_FILTER",
             "KUBERNETES_SERVICE_HOST",
             "DOCKERFILE_NODE_DEFAULT_PATH",
             "RENOVATE_CE_MEND_RENOVATE_CE_SERVICE_PORT_HTTP",
             "LC_ALL",
             "KUBERNETES_PORT",
             "KUBERNETES_PORT_443_TCP_PORT",
             "PATH",
             "CONTAINERBASE_ENV",
             "MEND_RNV_GITLAB_PAT",
             "CGO_ENABLED",
             "RUST_BACKTRACE",
             "npm_config_update_notifier",
             "RENOVATE_CE_MEND_RENOVATE_CE_SERVICE_HOST",
             "DEBIAN_FRONTEND",
             "GOPATH",
             "_",
             "GIT_SSH_COMMAND",
             "RENOVATE_AUTODISCOVER",
             "RENOVATE_CONFIG"
           ],
           "maxBuffer": null,
           "stdio": "inherit",
           "timeout": 3600000
         },
         "exitCode": 1,
         "name": "ExecError",
         "message": "Command failed: /usr/bin/node_default /usr/src/app/node_modules/renovate/dist/renovate.js\n",
         "stack": "ExecError: Command failed: /usr/bin/node_default /usr/src/app/node_modules/renovate/dist/renovate.js\n\n    at ChildProcess.<anonymous> (/usr/src/app/node_modules/renovate/dist/util/exec/common.js:87:24)\n    at ChildProcess.emit (node:events:529:35)\n    at ChildProcess.emit (node:domain:489:12)\n    at ChildProcess._handle.onexit (node:internal/child_process:292:12)"
       }
DEBUG: Renovate job finished
       "status": "cli-error"
DEBUG: No new job to execute - waiting 15 seconds
DEBUG: No new job to execute - waiting 15 seconds
```

**Comment by missedone** [comment]
Yes, that’s the strange part, as the onboard PR was created, which means the hit lab token works?

**Comment by rarkins** [comment]
Yes, but it doesn't mean that something didn't change.

You should do this:
- For this repo which is erroring, compare the log from when the onboarding was done to now
- If it doesn't error for every repo, compare the logs for one which works and one which doesn't

**Comment by missedone** [comment]
<img width="1646" alt="image" src="https://github.com/mend/renovate-ce-ee/assets/555134/88a0c19c-d987-4b1e-a64a-9bddb6c9bb66">

on the same repo, some branches/PRs were created successfully, but others failed , it did looks like a config issue

**Comment by missedone** [comment]
pls let me know how can i better help you troubleshooting on this issue

**Comment by rarkins** [comment]
The error message "empty message from server" implies that you have a local problem and it's not a Renovate or config problem.

You should Google this error term to see if any of the results help you, I cannot help you.

Example: https://forum.gitlab.com/t/runner-unable-to-access-via-gitlab-ci-token-empty-reply-from-server/32779
