### ISSUE TITLE
'EACCESS permission denied' when using install-tool

### ISSUE THREAD

**Issue by buffcode** [mend/renovate-ce-ee#606]
After switching to the v8 images we have severe issues with our setup, because the MRs won't be updated correctly anymore.

When Renovatebot tries to install the detected Yarn version, it fails with
```
ERROR (14995): EACCES: permission denied, mkdir '/opt/containerbase/tools/yarn-slim'

ExecError: Command failed: install-tool yarn-slim 1.22.22
  at ChildProcess.<anonymous> (/usr/src/app/node_modules/renovate/lib/util/exec/common.ts:101:11)
  at ChildProcess.emit (node:events:531:35)
  at ChildProcess.emit (node:domain:488:12)
  at Process.ChildProcess._handle.onexit (node:internal/child_process:294:12)
```

`/opt/containerbase` withing the container belongs to `root`, while the tool tries to install with uid 1000 `renovate`.

I found https://github.com/renovatebot/renovate/discussions/26143, but that was merged almost a year ago.

I have completely reset my containers using `docker compose down -v -t 0` followed by `docker compose up -d --build`.

<details>
<summary>docker-compose.yaml</summary>

```yaml
# docker-compose.yaml
x-controller-shared-variables: &variables-controller
  MEND_RNV_SERVER_HOSTNAME: http://renovate:8080
  MEND_RNV_SERVER_API_SECRET: "<redacted>"
  MEND_RNV_ACCEPT_TOS: "y"
  MEND_RNV_LICENSE_KEY: "<redacted>"
  LOG_LEVEL: "debug"

services:
  renovate:
    build:
      context: .
    restart: unless-stopped
    environment:
      <<: *variables-controller
      GITHUB_COM_TOKEN: "<redacted>"
      MEND_RNV_PLATFORM: "gitlab"
      MEND_RNV_ENDPOINT: "<redacted>
      MEND_RNV_WEBHOOK_SECRET: "<redacted>"
      MEND_RNV_GITLAB_PAT: "<redacted>"
    ports:
      - 172.17.0.1:8092:8080
    volumes:
      - ./.npmrc:/home/ubuntu/.npmrc:ro
      - ./config.js:/usr/src/app/config.js:ro
      - ./config:/usr/src/app/custom_config:ro
      - cache:/tmp/renovate-cache
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: 'redis-server --maxmemory 1500mb --maxmemory-policy allkeys-lru --appendonly yes'
    volumes:
      - redis:/usr/local/etc/redis

volumes:
  cache:
  redis:
```
</details>

<details>
<summary>Dockerfile</summary>

```Dockerfile
FROM ghcr.io/mend/renovate-ce:8.6.0-full

RUN pip install setuptools packaging
```
</details>

<details>
<summary>Logs</summary>

```
DEBUG: lock file error (repository=<redacted>, branch=renovate/nodemon-3.1.x)
       "err": {
         "cmd": "/bin/sh -c install-tool yarn-slim 1.22.22",
         "stderr": "",
         "stdout": "[22:50:39.250] INFO (14995): Installing tool yarn-slim@1.22.22...\n[22:50:39.295] ERROR (14995): EACCES: permission denied, mkdir '/opt/containerbase/tools/yarn-slim'\n[22:50:39.296] FATAL (14995): Install tool yarn-slim failed in 53ms.\n",
         "options": {
           "cwd": "/tmp/renovate/repos/gitlab/<redacted>",
           "encoding": "utf-8",
           "env": {
             "NPM_CONFIG_CACHE": "/tmp/renovate-cache/others/npm",
             "npm_config_store": "/tmp/renovate-cache/others/pnpm",
             "CI": "true",
             "YARN_CACHE_FOLDER": "/tmp/renovate-cache/others/yarn",
             "HOME": "/home/ubuntu",
             "PATH": "/home/ubuntu/.local/bin:/home/ubuntu/bin:/home/ubuntu/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
             "LC_ALL": "C.UTF-8",
             "LANG": "C.UTF-8",
             "CONTAINERBASE_CACHE_DIR": "/tmp/renovate-cache/containerbase"
           },
           "maxBuffer": 10485760,
           "timeout": 900000
         },
         "exitCode": 1,
         "name": "ExecError",
         "message": "Command failed: install-tool yarn-slim 1.22.22\n",
         "stack": "ExecError: Command failed: install-tool yarn-slim 1.22.22\n\n    at ChildProcess.<anonymous> (/usr/src/app/node_modules/renovate/lib/util/exec/common.ts:101:11)\n    at ChildProcess.emit (node:events:531:35)\n    at ChildProcess.emit (node:domain:488:12)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:294:12)"
       },
       "type": "yarn"
```
</details>

<details>
<summary>Reproduction</summary>

```
$ docker compose exec renovate install-tool yarn-slim 1.22.22

[01:48:55.064] DEBUG (29729): discovered distro
    distro: {
      "name": "Ubuntu",
      "versionCode": "focal",
      "versionId": "20.04"
    }
[01:48:55.067] DEBUG (29729): prepare commands
[01:48:55.081] DEBUG (29729): Try resolving version for yarn-slim@1.22.22 ...
[01:48:55.089] INFO (29729): Installing tool yarn-slim@1.22.22...
[01:48:55.102] DEBUG (29729): validate tool
    tool: "yarn-slim"
[01:48:55.104] DEBUG (29729): install tool
    tool: "yarn-slim"
[01:48:55.130] DEBUG (29729): EACCES: permission denied, mkdir '/opt/containerbase/tools/yarn-slim'
    err: {
      "type": "Error",
      "message": "EACCES: permission denied, mkdir '/opt/containerbase/tools/yarn-slim'",
      "stack":
          Error: EACCES: permission denied, mkdir '/opt/containerbase/tools/yarn-slim'
              at async Object.mkdir (node:internal/fs/promises:858:10)
              at async PathService.createDir (/snapshot/dist/containerbase-cli.js:46423:5)
              at async PathService.createToolPath (/snapshot/dist/containerbase-cli.js:46428:5)
              at async PathService.ensureToolPath (/snapshot/dist/containerbase-cli.js:46432:45)
              at async YarnSlimInstallService.install (/snapshot/dist/containerbase-cli.js:56839:5)
              at async YarnSlimInstallService.install (/snapshot/dist/containerbase-cli.js:57163:5)
              at async InstallToolService.execute (/snapshot/dist/containerbase-cli.js:58281:11)
              at async InstallToolShortCommand.execute (/snapshot/dist/containerbase-cli.js:58596:14)
              at async InstallToolShortCommand.validateAndExecute (/snapshot/dist/containerbase-cli.js:2428:26)
              at async _Cli.run (/snapshot/dist/containerbase-cli.js:3541:22)
      "errno": -13,
      "code": "EACCES",
      "syscall": "mkdir",
      "path": "/opt/containerbase/tools/yarn-slim"
    }
[01:48:55.130] ERROR (29729): EACCES: permission denied, mkdir '/opt/containerbase/tools/yarn-slim'
[01:48:55.131] FATAL (29729): Install tool yarn-slim failed in 53ms.

```
</details>

**Comment by nabeelsaabna** [comment]
also following your example `install-tool` passes without permissions problems:

`❯ docker compose up -d --build`
```
[+] Building 0.1s (7/7) FINISHED                                                                                                                                                                                                                                                                             docker:default
 => [renovate internal] load build definition from Dockerfile                                                                                                                                                                                                                                                          0.0s
 => => transferring dockerfile: 138B                                                                                                                                                                                                                                                                                   0.0s
 => [renovate internal] load metadata for ghcr.io/mend/renovate-ce:8.6.0-full                                                                                                                                                                                                                                          0.0s
 => [renovate internal] load .dockerignore                                                                                                                                                                                                                                                                             0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                                                                        0.0s
 => [renovate 1/2] FROM ghcr.io/mend/renovate-ce:8.6.0-full                                                                                                                                                                                                                                                            0.0s
 => CACHED [renovate 2/2] RUN pip install setuptools packaging                                                                                                                                                                                                                                                         0.0s
 => [renovate] exporting to image                                                                                                                                                                                                                                                                                      0.0s
 => => exporting layers                                                                                                                                                                                                                                                                                                0.0s
 => => writing image sha256:776ce01755ec64d1073433f003458c288e3fe22eb0f14db77eecb5c969fb0e9b                                                                                                                                                                                                                           0.0s
 => => naming to docker.io/library/perm-reproduction-renovate                                                                                                                                                                                                                                                          0.0s
 => [renovate] resolving provenance for metadata file                                                                                                                                                                                                                                                                  0.0s
[+] Running 3/3
 ✔ Network perm-reproduction_default       Created                                                                                                                                                                                                                                                                     0.1s 
 ✔ Container perm-reproduction-redis-1     Started  
```

`❯ docker compose exec renovate install-tool yarn-slim 1.22.22`
```
[07:41:33.906] DEBUG (9): discovered distro
    distro: {
      "name": "Ubuntu",
      "versionCode": "focal",
      "versionId": "20.04"
    }
[07:41:33.906] DEBUG (9): prepare commands
[07:41:33.909] DEBUG (9): Try resolving version for yarn-slim@1.22.22 ...
[07:41:33.910] INFO (9): Installing tool yarn-slim@1.22.22...
[07:41:33.914] DEBUG (9): validate tool
    tool: "yarn-slim"
[07:41:33.914] DEBUG (9): install tool
    tool: "yarn-slim"
[07:41:33.916] DEBUG (9): setting path mode
    path: "/opt/containerbase/tools/yarn-slim"
    mode: 509
    s: 493
[07:41:33.916] DEBUG (9): setting path mode
    path: "/opt/containerbase/tools/yarn-slim/1.22.22"
    mode: 509
    s: 493
[07:41:33.916] DEBUG (9): setting path mode
    path: "/opt/containerbase/tools/yarn-slim/1.22.22/20.18.0"
    mode: 509
    s: 493
1.22.22
[07:41:34.709] DEBUG (9): tool version not found
    tool: "yarn-slim"
[07:41:34.709] DEBUG (9): link tool
    tool: "yarn-slim"
[07:41:34.712] DEBUG (9): post-install tool
    tool: "yarn-slim"
[07:41:34.713] DEBUG (9): test tool
    tool: "yarn-slim"
[07:41:34.853] INFO (9): Install tool yarn-slim succeeded in 945ms.
```

`❯ docker compose down`
```
[+] Running 3/3
 ✔ Container perm-reproduction-renovate-1  Removed                                                                                                                                                                                                                                                                     0.2s 
 ✔ Container perm-reproduction-redis-1     Removed                                                                                                                                                                                                                                                                     0.2s 
 ✔ Network perm-reproduction_default       Removed                                                                                                                                                                                                                                                                     0.1s 
```

**Comment by buffcode** [comment]
Hm yeah, indeed it works in a fresh container setup.

I executed the install-tools command after discovering it's failure in the container which already ran about a day. In this container it is reproducible, but I have no clue how to reproduce that state at the moment expect for waiting.

**Comment by nabeelsaabna** [comment]
If issue is reproduced please reopen the issue with more info
